/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipp.estg.pages.chats.messages;

import ipp.estg.models.User;
import ipp.estg.pages.chats.channelList.*;
import ipp.estg.Client;
import ipp.estg.constants.CommandsFromClient;
import ipp.estg.models.Channel;
import ipp.estg.pages.chats.channelChat.ChannelChatPage;
import ipp.estg.pages.chats.privateChat.PrivateChatPage;
import ipp.estg.pages.main.MainPage;
import ipp.estg.utils.JsonConverter;

import javax.swing.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author User
 */
public class UserMessagesListPage extends javax.swing.JFrame {

    private final Client client;

    /**
     * Map to store Users and its respective index on the list.
     * Because the selected index of the list and the User Id might be different
     */
    private final Map<String, User> userToUserMap = new HashMap<>();

    /**
     * Creates new form CreateGroupPage
     */
    public UserMessagesListPage(Client client) {
        this.client = client;

        initComponents();
        loadChannelsToList();
    }

    private void loadChannelsToList() {
        groupList.removeAll();
        userToUserMap.clear();

        // Get channels (GET_USERS )
        String request = CommandsFromClient.GET_USERS;
        String response = client.sendMessageToServer(request);

        // Parse response
        JsonConverter jsonConverter = new JsonConverter();
        List<User> allUsers = jsonConverter.fromJsonToList(response, User.class);

        int indexOnList = 0;
        for (User user : allUsers) {
            // Skip logged user
            String loggedUserId = client.getLoggedUserId();
            String userId = Integer.toString(user.getId());
            if(loggedUserId.equals(userId)) {
                continue;
            }

            // add user to Map
            String indexOnListString = Integer.toString(indexOnList);
            userToUserMap.put(indexOnListString, user);

            // add user to list
            groupList.add(
                    user.getUsername()
            );

            indexOnList++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupList = new java.awt.List();
        backBtn = new javax.swing.JButton();
        openChatBtn = new javax.swing.JButton();
        errorLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        openChatBtn.setText("Open Chat");
        openChatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openChatBtnActionPerformed(evt);
            }
        });

        errorLbl.setForeground(new java.awt.Color(255, 0, 0));
        errorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("Users");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(backBtn)
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(groupList, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(errorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(openChatBtn)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupList, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(openChatBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        MainPage mainPage = new MainPage(client);
        mainPage.setVisible(true); // open mainPage
        this.dispose(); // close current page
    }//GEN-LAST:event_backBtnActionPerformed

    private void openChatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openChatBtnActionPerformed

        int selectedIndex = groupList.getSelectedIndex();
        if (selectedIndex == -1) {
            errorLbl.setText("Select a user to send a message");
            return;
        }

        // Get channel from Map
        String selectedIndexString = Integer.toString(selectedIndex);
        User selectedUser = userToUserMap.get(selectedIndexString);

        // Open Channel Chat Page
        PrivateChatPage chatPage = new PrivateChatPage(client, selectedUser);
        chatPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_openChatBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel errorLbl;
    private java.awt.List groupList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton openChatBtn;
    // End of variables declaration//GEN-END:variables
}
